# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# 통과해야지만 Merge 되게 하기
name: Python package
on: 
  push:
    branches: [ "main" ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        poetry-version: ["1.2.2", "1.7.1"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1
      # - uses: actions/checkout@v4
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}
      # - name: Run image
      #   uses: abatilo/actions-poetry@v2
      #   with:
      #     poetry-version: ${{ matrix.poetry-version }}
      # - name: View poetry --help
      #   run: poetry --help
    - name: Install dependencies
      run: |
        poetry shell
        poetry install
    
    - name: Test with pytest
      run: |
        pytest
        